### ISSUE TITLE
Sel.SecretKey.Cipher.newSecretKey segfaults

### ISSUE THREAD

**Issue by ptitfred** [haskell-cryptography/libsodium-bindings#115]
I'm afraid the cipher fails with a segfault with current version of `sel`.

Tested with current main (06ea49cb4ded582b318b88d623816b090ca9679e) and libsodium 1.0.18 [provided by nixpkgs-23.05](https://github.com/NixOS/nixpkgs/blob/5cfafa12d57374f48bcc36fda3274ada276cf69e/pkgs/development/libraries/libsodium/default.nix).

In a repl, simply do:
```
> import Sel.SecretKey.Cipher
> newSecretKey
```

If I'm missing something, let me know.

**Comment by ptitfred** [comment]
The system logs for a similar test case in a proper executable:

```
systemd-coredump[1009]: Process 1001 (backoffice-back) of user 0 dumped core.

Module libkeyutils.so.1 without build-id.
Module libkrb5support.so.0 without build-id.
Module libcom_err.so.3 without build-id.
Module libk5crypto.so.3 without build-id.
Module libkrb5.so.3 without build-id.
Module libgssapi_krb5.so.2 without build-id.
Module libffi.so.8 without build-id.
Module libgmp.so.10 without build-id.
Module libz.so.1 without build-id.
Module backoffice-backend without build-id.
Stack trace of thread 1001:
#0  0x00007f29a1005adc __pthread_kill_implementation (libc.so.6 + 0x87adc)
#1  0x00007f29a0fb6cb6 raise (libc.so.6 + 0x38cb6)
#2  0x00007f29a0fa08ba abort (libc.so.6 + 0x228ba)
#3  0x00007f29a128bc2a sodium_misuse.cold (libsodium.so.23 + 0xec2a)
#4  0x00007f29a12a611d sodium_malloc (libsodium.so.23 + 0x2911d)
#5  0x0000000000425959 n/a (backoffice-backend + 0x25959)
#6  0x0000000000425427 n/a (backoffice-backend + 0x25427)
ELF object binary architecture: AMD x86-64
```

**Comment by ptitfred** [comment]
My bad ; after calling `sodiumInit` it works better.

**Comment by Kleidukos** [comment]
Very well, so it's a documentation issue. Would you be satisfied with a warning in the module documentation, or could something more be done?

**Comment by ptitfred** [comment]
I'm tempted to submit a pull request to patch [`newSecretKeyWith`](https://hackage.haskell.org/package/sel-0.0.1.0/candidate/docs/Sel-SecretKey-Cipher.html#v:newSecretKeyWith) so that `sodiumInit` is called (as it's safe to call it multiple times). wdyt?

**Comment by kozross** [comment]
@ptitfred and @Kleidukos - we have `secureMain` to prevent exactly this sort of problem. `sel` doesn't seem to export it for some reason, though.

**Comment by Kleidukos** [comment]
Yes, Sel should export it

**Comment by Kleidukos** [comment]
> I'm tempted to submit a pull request to patch [`newSecretKeyWith`](https://hackage.haskell.org/package/sel-0.0.1.0/candidate/docs/Sel-SecretKey-Cipher.html#v:newSecretKeyWith) so that `sodiumInit` is called (as it's safe to call it multiple times). wdyt?

I've looked at [its source](https://github.com/jedisct1/libsodium/blob/7e3500e878ee5a3a286705ea646a535b33a29cd3/src/libsodium/sodium/core.c#L28-L60) and while the operations involved don't seem to be too expensive, I'd like to see first if guiding users to use `secureMain` works too.

**Comment by kozross** [comment]
I would say `secureMain` is the right approach. If you're a library author, initialization isn't your problem; if you're writing an executable (or test, or benchmark), you want to initialize once, then never have to think about it again. This parallels what libraries like `tasty` do with `main`, for example.

**Comment by ptitfred** [comment]
If it's expensive let's call it once. I'm afraid though that having an init function to call can be missed too but the library user. I guess it's a matter of documentation exhaustiveness.

**Comment by ptitfred** [comment]
Thank you both 🙇

**Comment by Kleidukos** [comment]
Thank you for the early feedback, this is extremely valuable. :)

**Comment by kozross** [comment]
> If it's expensive let's call it once. I'm afraid though that having an init function to call can be missed too by the library user. I guess it's a matter of documentation exhaustiveness.

This is unfortunately forced on us by `libsodium` itself. It's not an unusual convention in the C world: you have a global `init_whatever` function called once for the whole program which sets some kind of global state, which then gets used throughout. Not very Haskelly, but it doesn't leave us many options.

**Comment by Kleidukos** [comment]
Yes there is certainly something to explore in effect systems.
