### ISSUE TITLE
Add SecretStream API to `sel`

### ISSUE THREAD

**Issue by Kleidukos** [haskell-cryptography/libsodium-bindings#141]
Let's add a high-level interface to https://hackage.haskell.org/package/libsodium-bindings/docs/LibSodium-Bindings-SecretStream.html in `sel`.

@domenkozar I would love to hear about your use-case, this will help us define the initial scope and write tests. :)

**Comment by domenkozar** [comment]
I'd like to replace https://hackage.haskell.org/package/crypton-conduit-0.2.3/docs/Crypto-Cipher-ChaChaPoly1305-Conduit.html with libsodium :)

**Comment by Kleidukos** [comment]
@domenkozar okay, are you tied with `conduit` as the streaming library?

**Comment by domenkozar** [comment]
At the moment, yes.

Long term I want to switch to streamly and that requires quite a bit of code writing.

**Comment by Kleidukos** [comment]
Alright, so in order to make the transition smooth we'd have to have an IO-based solution that could be plugged into Conduit, streamly and the rest.
