### ISSUE TITLE
Expose constant-time serialisation primitives from libsodium

### ISSUE THREAD

**Issue by Kleidukos** [haskell-cryptography/libsodium-bindings#15]
We should expose the constant-time serialisation primitives from libsodium, for hexadecimal and base64.

## Is blocked by

* [x] https://gitlab.haskell.org/ghc/ghc/-/issues/15531 -- Now available since GHC 9.2.2

**Comment by kpadmasola** [comment]
@Kleidukos I'd like to contribute to this to improve my Haskell knowledge. I am a beginner in Haskell, but have started doing a few minor contributions to other Haskell repos. 

Can you please share some pointers on how I should get started with fixing this issue? 

Is there a Discord channel where I can reachout to the maintainers of this codebase for questions?

Thank you!

**Comment by Kleidukos** [comment]
fixed by #33
