### ISSUE TITLE
Module hierarchy for symmetric and asymmetric cryptography

### ISSUE THREAD

**Issue by Kleidukos** [haskell-cryptography/libsodium-bindings#73]
I'm not super certain what I would like this module hierarchy to look like. I see several options for the symmetric cryptography:

* `Sel.SecretKey.AuthenticatedEncryption`
* `Sel.SecretKey.AuthenticatedStream`
* `Sel.SecretKey.Authentication`

or

* `Sel.SecretBox`
* `Sel.SecretStream`
* `Sel.Auth`

For asymmetric cryptography the names given by libsodium would be

* `Sel.PublicKey.AuthenticatedEncryption`
* `Sel.PublicKey.Signature`
* `Sel.PublicKey.SealedBox`

or

* `Sel.Box`
* `Sel.Sign`
* `Sel.Seal`

@kozross @divarvel @a-02 @axman6 what do you think?

**Comment by divarvel** [comment]
Are there equivalents for asymmetric crypto / a risk of name collisions?

**Comment by a-02** [comment]
As much as I love slick short module names, the longer ones are better. To me, module names should provide at-a-glance information about what that module does.

**Comment by kozross** [comment]
I don't per-se mind the longer names as long as they're informative.

**Comment by Kleidukos** [comment]
Last point of bikeshedding and then I swear I'll stop:

SecretKey / PublicKey or Symmetric/Asymmetric ?

**Comment by divarvel** [comment]
I'd say striving for consistency with libsodium is good, so `SecretKey` / `PublicKey` would be better, since it's what libsodium uses

**Comment by Kleidukos** [comment]
Thanks everyone, the chosen scheme is `SecretKey` / `PublicKey`.
