### ISSUE TITLE
CI badges link to the wrong url

### ISSUE THREAD

**Issue by monadplus** [haskell-cryptography/libsodium-bindings#85]
Badges should be of the form [![sel-badge]][sel-ci] i.e. `[![sel-badge]][sel-ci]` where 

```
[sel-badge]: https://github.com/haskell-cryptography/libsodium-bindings/actions/workflows/sel.yml/badge.svg
[sel-ci]: https://github.com/haskell-cryptography/libsodium-bindings/actions/workflows/sel.yml?query=branch%3Amain
```

[sel-badge]: https://github.com/haskell-cryptography/libsodium-bindings/actions/workflows/sel.yml/badge.svg
[sel-ci]: https://github.com/haskell-cryptography/libsodium-bindings/actions/workflows/sel.yml?query=branch%3Amain

**Comment by Kleidukos** [comment]
closed via  #92
