### ISSUE TITLE
Zeroing ForeignPtrs on deallocation

### ISSUE THREAD

**Issue by dpwiz** [haskell-cryptography/libsodium-bindings#88]
Given all the warnings and "[REDACTED]" instances I was surprised that there are no memory clean-up for those objects.

Perhaps there should be an `mallocForeignPtrBytes` wrapper that automatically attaches `addForeignPtrFinalizer` with `fillBytes` or `sodium_memzero()`.

OTOH, when you import your secrets from a `ByteString` or hex, it's already a game over in this department :woman_shrugging:

**Comment by dpwiz** [comment]
Or just go all in on `sodium_malloc()`.

**Comment by Kleidukos** [comment]
Certainly sodium_malloc() could be used, yes.
Do you feel like you'd like to tackle this? :)

**Comment by tchoutri** [comment]
closed via #91
